Vagrant.configure(2) do |config|

  config.vm.define "chefnodeA" do |chefnodeA|
    chefnodeA.vm.box = "puphpet/centos65-x64"
    chefnodeA.vm.hostname = "chefnode1A"
    chefnodeA.vm.network "private_network", ip: "192.168.22.10"
    chefnodeA.vm.network "forwarded_port", guest: 8080, host: 8081
  end

  config.vm.define "chefnodeB" do |chefnodeB|
    chefnodeB.vm.box = "puphpet/centos65-x64"
    chefnodeB.vm.hostname = "chefnode1B"
    chefnodeB.vm.network "private_network", ip: "192.168.22.20"
    chefnodeB.vm.network "forwarded_port", guest: 8080, host: 8082
  end
  
end
